# Supported funding platforms for your project

github: [washycms13]          # Your GitHub username (if you apply for GitHub Sponsors)
patreon: washycms_patreon     # Replace with your Patreon username
open_collective: nilo-project # Replace with your Open Collective project name
ko_fi: washycms13             # Replace with your Ko-fi username
tidelift: npm/nilo            # Example if you publish to npm (adjust if needed)
community_bridge: cloud-foundry # Example project name, replace if you join
liberapay: washycms13         # Replace with your Liberapay username
issuehunt: washycms13         # Replace with your IssueHunt username
lfx_crowdfunding: nilo        # Replace with your LFX project name
polar: washycms13             # Replace with your Polar username
buy_me_a_coffee: washycms13   # Replace with your Buy Me a Coffee username
thanks_dev: washycms13        # Replace with your thanks.dev username
custom: ['https://yourwebsite.com/donate', 'https://paypal.me/yourname']
